-- Production security baseline. Apply once in a staging project, run the
-- verification queries in docs/PRODUCTION_READINESS.md, then promote.
-- Legacy supabase/*.sql files are NOT deployment migrations.

create type public.app_role as enum ('technician', 'junior', 'senior', 'super_admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role public.app_role not null default 'technician',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

create or replace function public.current_app_role()
returns public.app_role language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() and active $$;

create or replace function public.is_privileged()
returns boolean language sql stable security definer set search_path = public
as $$ select public.current_app_role() in ('junior', 'senior', 'super_admin') $$;

create or replace function public.is_super_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select public.current_app_role() = 'super_admin' $$;

revoke all on function public.current_app_role() from public;
revoke all on function public.is_privileged() from public;
revoke all on function public.is_super_admin() from public;
grant execute on function public.current_app_role(), public.is_privileged(), public.is_super_admin() to authenticated;

-- Existing admin credentials are intentionally quarantined. Create matching
-- auth.users and profiles through the protected admin-management Edge Function;
-- never copy password hashes to the browser or seed a default administrator.
revoke all on table public.admins from anon, authenticated;
alter table public.admins enable row level security;

alter table public.records add column if not exists created_by uuid references auth.users(id);
alter table public.records add column if not exists updated_by uuid references auth.users(id);
alter table public.records add column if not exists updated_at timestamptz not null default now();
alter table public.activity_logs add column if not exists actor_id uuid references auth.users(id);
alter table public.activity_logs add column if not exists result text not null default 'success';
alter table public.activity_logs add column if not exists metadata jsonb not null default '{}'::jsonb;

create or replace function public.set_record_actor()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
  if tg_op = 'INSERT' then new.created_by := auth.uid(); end if;
  new.updated_by := auth.uid(); new.updated_at := now();
  return new;
end $$;
drop trigger if exists records_set_actor on public.records;
create trigger records_set_actor before insert or update on public.records
for each row execute function public.set_record_actor();

-- Remove every legacy policy. RLS is deny-by-default until the exact policies below exist.
do $$ declare p record; begin
  for p in select schemaname, tablename, policyname from pg_policies where schemaname in ('public','storage') loop
    execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

alter table public.records enable row level security;
create policy records_read on public.records for select to authenticated using (public.current_app_role() is not null);
create policy records_insert on public.records for insert to authenticated with check (
  public.current_app_role() is not null and created_by = auth.uid() and updated_by = auth.uid());
create policy records_update on public.records for update to authenticated using (public.is_privileged()) with check (public.is_privileged() and updated_by = auth.uid());
create policy records_delete on public.records for delete to authenticated using (public.current_app_role() in ('senior','super_admin'));

alter table public.settings enable row level security;
create policy settings_read on public.settings for select to authenticated using (public.current_app_role() is not null);
create policy settings_write on public.settings for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());

alter table public.activity_logs enable row level security;
create policy activity_logs_read on public.activity_logs for select to authenticated using (public.is_privileged());
-- No client INSERT, UPDATE, or DELETE policy: audit events must be generated by trusted code.

alter table public.inspection_evidence add column if not exists uploaded_by uuid references auth.users(id);
alter table public.inspection_evidence enable row level security;
create policy evidence_read on public.inspection_evidence for select to authenticated using (public.current_app_role() is not null);
create policy evidence_insert on public.inspection_evidence for insert to authenticated with check (uploaded_by = auth.uid());
create policy evidence_delete on public.inspection_evidence for delete to authenticated using (public.is_privileged());

-- Private evidence: user UUID must be the first object-path segment.
update storage.buckets set public = false where id = 'inspection-evidence';
create policy evidence_object_read on storage.objects for select to authenticated using (
  bucket_id = 'inspection-evidence' and (owner_id = auth.uid() or public.is_privileged()));
create policy evidence_object_insert on storage.objects for insert to authenticated with check (
  bucket_id = 'inspection-evidence' and owner_id = auth.uid() and (storage.foldername(name))[1] = auth.uid()::text);
create policy evidence_object_delete on storage.objects for delete to authenticated using (
  bucket_id = 'inspection-evidence' and (owner_id = auth.uid() or public.is_privileged()));

create policy profiles_self_read on public.profiles for select to authenticated using (id = auth.uid());
create policy profiles_privileged_read on public.profiles for select to authenticated using (public.is_super_admin());

-- The data model and schema migration discipline are explicit release gates.
create unique index if not exists records_submission_id_unique on public.records(submission_id) where submission_id is not null;
create index if not exists records_submitted_at_idx on public.records(submitted_at desc);
create index if not exists inspection_evidence_uploaded_by_idx on public.inspection_evidence(uploaded_by);
